## Numpy Maths Concepts

In [ ]:
import numpy as np
a=[1,2,3]
b=[4,5,6]

print(a+b) # Here It is not adding the actual but kind of concatination , this is not what we want

aa=np.array([1,2,3])
bb=np.array([4,5,6])

print(aa+bb) #this will have the actual addition

''' 
The operation using python will make use of loops but in numpy it make use of Vectorization
So it we talk about add,sub,multiplication operation in numpy it will be doing element wise operation
It is not the same add, sub, mutiplication operation as in python

What is vetorization..?

Calculation which does not make use of the loops in order to  calculate something rather it will make use vectors to calculate the things(Internally these vevtors are feed to cpu to genrate results of the calculatin)
In the above addition of arrray internally numpy will directly pass the (1+4),(2+5),(3+6) to the cpu and cpu will generate the rsut for tha calculation
Vector
ization is performed by numpy sp cpu make use it as input

'''

'''
Vectorization in NumPy

In pure Python, operations on collections of numbers are usually performed using loops:

a = [1, 2, 3]
b = [4, 5, 6]

result = []
for i in range(len(a)):
    result.append(a[i] + b[i])

print(result)
# [5, 7, 9]

With NumPy, the same operation can be performed directly on arrays:

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = a + b

print(result)
# [5 7 9]
What is Vectorization?

Vectorization is the process of performing operations on entire arrays (vectors) at once, rather than iterating through elements using explicit Python loops.

NumPy uses highly optimized C code internally. Instead of Python executing:

(1+4)
(2+5)
(3+6)

one by one in a loop, NumPy passes the arrays to low-level optimized routines, which process many elements efficiently. These routines may take advantage of CPU features such as SIMD (Single Instruction Multiple Data), allowing multiple values to be computed simultaneously.

Element-wise Operations

For two arrays of the same shape:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

Addition:

a + b
# [5 7 9]

Subtraction:

a - b
# [-3 -3 -3]

Multiplication:

a * b
# [4 10 18]

Division:

a / b
# [0.25 0.4 0.5]

These are element-wise operations:

a = [1, 2, 3]
b = [4, 5, 6]

Addition:
[(1+4), (2+5), (3+6)] = [5, 7, 9]

Multiplication:
[(1×4), (2×5), (3×6)] = [4, 10, 18]
Why is Vectorization Faster?
No explicit Python loops.
Operations are implemented in optimized C code.
Better memory usage.
Can utilize CPU vector instructions (SIMD).
Significantly faster for large datasets.
In One Line

Vectorization is performing operations on entire arrays at once using optimized low-level code, instead of iterating element by element with Python loops.

This is one of the main reasons why NumPy is extremely fast and widely used in data science, machine learning, and scientific computing.

'''


[1, 2, 3, 4, 5, 6]
[5 7 9]


In [ ]:
# DOT Products
import numpy as np

aa=np.array([1,2,3])
bb=np.array([4,5,6])

print(np.dot(aa,bb)) # Dot product means mutiplicaton + summation

''' 
Facts for dot product

A--> m*n matrix
B--> n*p matrix

A.B--> m*p results of A.B will be m*p

'''
