## Numpy Maths Concepts

In [ ]:
import numpy as np
a=[1,2,3]
b=[4,5,6]

print(a+b) # Here It is not adding the actual but kind of concatination , this is not what we want

aa=np.array([1,2,3])
bb=np.array([4,5,6])

print(aa+bb) #this will have the actual addition

''' 
The operation using python will make use of loops but in numpy it make use of Vectorization
So it we talk about add,sub,multiplication operation in numpy it will be doing element wise operation
It is not the same add, sub, mutiplication operation as in python

What is vetorization..?

Calculation which does not make use of the loops in order to  calculate something rather it will make use vectors to calculate the things(Internally these vevtors are feed to cpu to genrate results of the calculatin)
In the above addition of arrray internally numpy will directly pass the (1+4),(2+5),(3+6) to the cpu and cpu will generate the rsut for tha calculation
Vector
ization is performed by numpy sp cpu make use it as input

'''

'''
Vectorization in NumPy

In pure Python, operations on collections of numbers are usually performed using loops:

a = [1, 2, 3]
b = [4, 5, 6]

result = []
for i in range(len(a)):
    result.append(a[i] + b[i])

print(result)
# [5, 7, 9]

With NumPy, the same operation can be performed directly on arrays:

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = a + b

print(result)
# [5 7 9]
What is Vectorization?

Vectorization is the process of performing operations on entire arrays (vectors) at once, rather than iterating through elements using explicit Python loops.

NumPy uses highly optimized C code internally. Instead of Python executing:

(1+4)
(2+5)
(3+6)

one by one in a loop, NumPy passes the arrays to low-level optimized routines, which process many elements efficiently. These routines may take advantage of CPU features such as SIMD (Single Instruction Multiple Data), allowing multiple values to be computed simultaneously.

Element-wise Operations

For two arrays of the same shape:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

Addition:

a + b
# [5 7 9]

Subtraction:

a - b
# [-3 -3 -3]

Multiplication:

a * b
# [4 10 18]

Division:

a / b
# [0.25 0.4 0.5]

These are element-wise operations:

a = [1, 2, 3]
b = [4, 5, 6]

Addition:
[(1+4), (2+5), (3+6)] = [5, 7, 9]

Multiplication:
[(1×4), (2×5), (3×6)] = [4, 10, 18]
Why is Vectorization Faster?
No explicit Python loops.
Operations are implemented in optimized C code.
Better memory usage.
Can utilize CPU vector instructions (SIMD).
Significantly faster for large datasets.
In One Line

Vectorization is performing operations on entire arrays at once using optimized low-level code, instead of iterating element by element with Python loops.

This is one of the main reasons why NumPy is extremely fast and widely used in data science, machine learning, and scientific computing.

'''


[1, 2, 3, 4, 5, 6]
[5 7 9]


In [ ]:
# DOT Products
import numpy as np

aa=np.array([1,2,3])
bb=np.array([4,5,6])

print(np.dot(aa,bb)) # Dot product means mutiplicaton + summation

''' 
Facts for dot product
1.
A--> m*n matrix
B--> n*p matrix

A.B--> results of A.B will be m*p

2. 
Columns of first matrix should match with rows of second matrix

3. when we dom the dot product of [1,2,3] , [4,5,6]  here the columns of firsty matrix is not equal to rows of secind matrix
   but it still gives the results

   What numoy does internaly is that it make the transpose of the seond matrix and produces the result and this is done only in 1 d matrix and not other

   It will be like [1,2,3], [4,
                             5,
                             6]

     Now the shape is 1*3 and other is 3*1

'''


In [ ]:
#Dot product
import numpy as np

a1=np.array([[1,2,3],[4,5,6]])
b1=np.array([[1,2,3],[4,5,6]])

print(a1.shape)

print(b1.shape)

#here column of 1st matrix and not equal to rows of second matrix
# np.dot(a1,b1) # this will give error due to obove metioned reaon
#Solution--> We can perform tranpose for anty one of them and carry out the dot product operation

#To MAke the tranpose of an arrray we make uisr of .T for any array

print(a1.T)

np.dot(a1,b1.T) #After transpose here the col of 1st matrix wil be equal rows of secod matrixx and then the dot product can be obtained



(2, 3)
(2, 3)
[[1 4]
 [2 5]
 [3 6]]


array([[14, 32],
       [32, 77]])

In [ ]:
import numpy as np

#Use Case , if we have the products and its prices stored in the array and we  nned the final result of sld products for each entity

Product_Prize= np.array(
    [
        [12,25,45,684,654], #Price of products in state-1
        [24,50,40,876,154]#Price of products in state-2
     ])


#This this the array of the quantity soldand above is the Produc prize
Quantity_Sold = np.array([
    [10,2,14,11,5], #State-1-price
    [2,3,4,5,6]     #State-2-price
    ])

# To get the total values of product sold we will need the dot product along with the transpose with any of the matrix

sales =np.dot(Product_Prize,Quantity_Sold.T)

''' 
[[state_1(price_of_state_1), state_1(Price of State-2)],

[state_2(price_of_state_1), state_2(Price of State-2)]]
'''

'''  
array([[11594,  7623],
       [11306,  5662]])
What does this matrix represent?
	Quantity of State-1	Quantity of State-2
Prices of State-1	11594 ✅	7623
Prices of State-2	11306	5662 ✅
Meaning of each value
11594 → Revenue if you use State-1 prices and State-1 quantities (actual revenue of State-1).
5662 → Revenue if you use State-2 prices and State-2 quantities (actual revenue of State-2).
7623 → Revenue if you hypothetically sold State-2 quantities using State-1 prices.
11306 → Revenue if you hypothetically sold State-1 quantities using State-2 prices.

'''

#Now to  ge the sum of the diagonnal

diag=np.eye(2) #this  will create the 2*2 matrix with 1 and 0 whose diagonakl  will be 1
print(diag)
np.sum(sales*diag)

'''  

Remember the difference
Operation	Meaning
A * B	Element-wise multiplication (each element is multiplied by the element at the same position)
A @ B or np.dot(A, B)	Matrix multiplication (rows of A are multiplied with columns of B)

This distinction is one of the most important concepts to understand when working with NumPy arrays.

'''

[[1. 0.]
 [0. 1.]]


np.float64(17256.0)

## Aggregation Function

In [1]:
import numpy as np

aa=np.array([1,2,3])

# Numpy gives usthe sum ,min, max of the array
print(np.sum(aa))
print(np.min(aa))
print(np.max(aa))

#1. argmax --> This will give the index of the highest element in the arrray

print(np.argmax(aa))

qq=[12,165,651,65,65,268552,56,949454844]
print(np.argmax(qq))
print(np.argmin(qq))

#2.sum


Product_Prize= np.array(
    [
        [12,25,45,684,654], #Price of products in state-1
        [24,50,40,876,154]#Price of products in state-2
     ])

np.sum(Product_Prize) # Sum will  give the addition of  the all element present in the matrix
print(np.sum(Product_Prize))

# Now column wise addition in which we specify axis=0

np.sum(Product_Prize,axis=0) # Here when axis=0 it will do the additon column wise [(12+24),(25+50),....], axis=0 means sum over rows, keep columns
print(np.sum(Product_Prize,axis=0))

# Now row  wise addition in which we specify axis=1

np.sum(Product_Prize,axis=1) # Here when axis=1 it will do the additon row wise wise [(12+25+45+684+654),(24+50+40+876+154)] , axis=1   -> means sum over rows, keep columns
print(np.sum(Product_Prize,axis=1))

#3. mean --> average --> sum of all elements and its average
np.mean(Product_Prize)
print(np.mean(Product_Prize))

np.mean(Product_Prize,axis=1) #--> sum of element in a row divide by number of elements --> (12+25+45+684+654)/5
print(np.mean(Product_Prize,axis=1))

np.mean(Product_Prize,axis=0) #--> sum of element in a column divide by number of elements (12+24)/2
print(np.mean(Product_Prize,axis=0))

#4. Standard Deviation
print(np.std(Product_Prize))
print(np.std(Product_Prize,axis=0))
print(np.std(Product_Prize,axis=1))


#Cumulative Sum  -> Whatever was the previous sum we are adding the new number

np.cumsum([1,2,3,4,5,6,7,8,9])
#[1,1+2,1+2+3,1+2+3+4,....]

#5. Median
np.median(Product_Prize)
print(np.median(Product_Prize))


np.median(Product_Prize,axis=1) 
print(np.median(Product_Prize,axis=1))

np.median(Product_Prize,axis=0) 
print(np.median(Product_Prize,axis=0))

#6.Percentile
np.percentile(qq,50)
print(np.percentile(qq,50))




6
1
3
2
7
0
2564
[  36   75   85 1560  808]
[1420 1144]
256.4
[284.  228.8]
[ 18.   37.5  42.5 780.  404. ]
321.98204918908135
[  6.   12.5   2.5  96.  250. ]
[314.66998586 326.8090574 ]
47.5
[45. 50.]
[ 18.   37.5  42.5 780.  404. ]
115.0


## Sort Search and Counting Function

In [ ]:

import numpy as np

arr2=np.array([3,6,1,1,1,8,2,5,6])

#Sort
print("sorted", np.sort(arr2))
#To get the index of sorted value
print("sorted indices", np.argsort(arr2))

''' 
np.argsort() does not return the sorted values.

It returns the indices (positions) that would sort the array.

np.argsort() does not return the sorted values.

It returns the indices (positions) that would sort the array.

Notice:

np.sort() → gives the sorted values
np.argsort() → gives the indices that produce the sorted order
'''
#2. searchsorted

print("Insert 4 position" , np.searchsorted(np.sort(arr2),4))

''' 
np.searchsorted() is one of the most useful NumPy functions when working with sorted arrays.

It answers this question:

"If I want to insert a value into a sorted array without disturbing the order, at which index should I insert it?"

Syntax
np.searchsorted(array, value)
array → Must be sorted.
value → The value you want to insert.
Example 1
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(np.searchsorted(arr, 35))

Output

3
Why?

Current array

Index	Value
0	10
1	20
2	30
3	40
4	50

Where should 35 go?

10 20 30 35 40 50

35 should be inserted before 40, which is index 3.

Hence

np.searchsorted(arr,35)

returns

3
Example 2

Insert 5

arr = np.array([10,20,30,40,50])

print(np.searchsorted(arr,5))

Output

0

Because

5 10 20 30 40 50

It goes at the beginning.

Example 3

Insert 60

print(np.searchsorted(arr,60))

Output

5

Why?

10 20 30 40 50 60

60 comes after the last element.

Visual Explanation

Suppose

arr = [10,20,30,40,50]
Index

0    1    2    3    4
|    |    |    |    |

10   20   30   40   50

Searching for 35

10   20   30   ?   40   50
              ↑
            index 3

So NumPy returns

3
Example 4 (Duplicates)
arr = np.array([10,20,20,20,30])

print(np.searchsorted(arr,20))

Output

1

Why?

Because by default

side='left'

It returns the first position where 20 can be inserted.

10 20 20 20 30
   ↑
 index 1
side='right'
arr = np.array([10,20,20,20,30])

print(np.searchsorted(arr,20,side='right'))

Output

4

Now NumPy inserts after the last 20.

10 20 20 20 30
            ↑
         index 4
Difference between left and right
arr = [10,20,20,20,30]
side='left'
10 |20|20|20|30
    ↑
  returns 1
side='right'
10|20|20|20| 30
             ↑
          returns 4
Multiple values

You can search for several values at once.

arr = np.array([10,20,30,40,50])

print(np.searchsorted(arr,[15,25,35,55]))

Output

[1 2 3 5]

Explanation

Value	Insert at Index
15	1
25	2
35	3
55	5
Real-life example

Imagine a sorted list of student marks:

marks = np.array([35,45,60,75,90])

new_mark = 70

index = np.searchsorted(marks,new_mark)

print(index)

Output

3

The new list would be:

35
45
60
70
75
90

70 should be inserted at index 3 to keep the marks sorted.

Difference between searchsorted() and argsort()
Function	Returns
np.sort(arr)	Sorted values
np.argsort(arr)	Indices that would sort the array
np.searchsorted(arr, x)	Index where x should be inserted into a sorted array
Easy way to remember
sort() → "Sort the array."
argsort() → "Tell me the order of indices needed to sort the array."
searchsorted() → "Tell me where a new value belongs in an already sorted array."

searchsorted() is especially useful in data science for maintaining sorted data efficiently, such as inserting timestamps, scores, prices, or other ordered values without re-sorting the entire array.

'''

#3. unique element

print(np.unique(arr2))
''' 
It returns only the unique (distinct) values from an array by removing duplicates. By default, the returned values are sorted in ascending order.
'''

# 4 bincount -->np.bincount() is a very fast NumPy function that counts how many times each non-negative integer appears in an array.
#Important: The array must contain non-negative integers (0, 1, 2, ...). It does not work with floats or negative numbers.

print(np.bincount(arr2))
''' 
here bincount will get the greatest element value and create the array from o to highest element
in arr2 largest num is 8  so it willl create the array like [0,1,2,3,4,5,6,7,8] and on this array it will start  counting

so in arr2 1 is 4 times so it will be[0 4 1 1 0 1 2 0 1]

'''
#

sorted [1 1 1 2 3 5 6 6 8]
sorted indices [3 2 4 6 0 7 1 8 5]
Insert 4 position 5
[1 2 3 5 6 8]
[0 3 1 1 0 1 2 0 1]


In [6]:
import numpy as np


# 1.Similar to range in Python we have arange in numpy which behaves same as python range

list(range(0,11)) # Range returns the object which needs to be converted into the list

np.arange(11)

arr3=np.arange(8).reshape(2,2,2)  #(Number of Blocks, Number of Rows, Number of Columns)
print(arr3)

# nditer --> np.nditer() is a NumPy function used to iterate over every element of an array, regardless of whether it is 1D, 2D, or 3D. It visits one element at a time in memory order.
# this is useful when you want to perform operations on each element of an array without explicitly using nested loops.
for element in np.nditer(arr3):
    print(element)

# 2.Copy --> this will create the copy of the array and any changes made to the copy will not affect the original array
a=np.array([1,2,3])
a_copy=a.copy()

print(id(a)) #this will have its own memoery location and a_copy will have its own memory location , both of them are independnt of each other
print(id(a_copy))

''' 
where as if we do
b=a # this will not create the copy of the array but it will create the reference of the original array and any changes made to b will affect a and vice versa

'''

#3. View --> this will create the view of the array and any changes made to the view will affect the original array and vice versa
a1=np.array([1,2,3])
a1_view=a1.view()  # this variable will have new object but will store the refrence to oroginal array and any changes made to this will affect the original array and vice versa
print(id(a1))
print(id(a1_view)) # Both will have the diffent mmory address but 

#To Check whther 2 array shares memoery we use np.sharesmemory(a1,a1_view) # this will return True if both the array shares the same memory location and False if they are independnt of each other
print(np.shares_memory(a1,a1_view)) # True

#Vstack --> np.vstack() stands for Vertical Stack. It joins arrays vertically, meaning it stacks one array below another (row-wise).



a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))

print(result)

#hstack --> np.hstack() stands for Horizontal Stack. It joins arrays horizontally, meaning it stacks one array next to another (column-wise).

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.hstack((a, b))

print(result)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
0
1
2
3
4
5
6
7
2639122253936
2639122259504
2639122259600
2639122255472
True
[[1 2 3]
 [4 5 6]]


## Numpy char and strings