In [ ]:
# lets compare the traditional python and numpy for adding two lists of numbers together
import time


a = list(range(1000000))
b = list(range(1000000))

start_p = time.perf_counter()
c = [x + y for x, y in zip(a, b)]
end_p = time.perf_counter()
total_p = end_p - start_p
print("Python:", total_p)

import numpy as np

a_np = np.array(a)
b_np = np.array(b)

start_n = time.perf_counter()
c_np = a_np + b_np
end_n = time.perf_counter()
total_n = end_n - start_n
print("NumPy:", total_n)

print(f"Numpy is faster than python by : {total_p/total_n:.2f}")

# Numpy uses vector for operations which is optimized for performance, while traditional python uses loops which can be slower for large datasets.

Python: 0.1684122890001163
NumPy: 0.008227457001339644
Numpy is faster than python by : 20.47


## Numpy

Python list are:
 - Flexible but slower numerical operations
 - Not designed for matrix math or
 - Does not support vectorised operation
 - Are memory inefficient for large numerical data

Why use Numpy..?
 - Numoy is fast than pure python for numerical computation
 - Use Vectorised operation i.e. here we dont have to write loops, does not uses loops,but does the same thing as loops does
 - Operates on arrays of different shape
 - Memory efficient
 - Allows Broadcasting --> Operate on arrays of different shape
 - Comes with powerful linear algebra, random tool etc
 
Use of numpy:
 - Scientific python 

In [ ]:
import numpy as np

#In python we have a list like [1,2,4,5,6,7,8,9] in pnumpy we call array which is a collection of elements of the same type. We can create an array using np.array() function.]


# Creating Arrays in numpy

 - np.array()

In [ ]:
import numpy as np  #
# 1 dimensionaal array
Arr = np.array([1,2,4,5,6,7,8,9]) # 1 dimensional array
print(Arr)  

#2 dimensional array
Arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(Arr_2d)

#2 dimensional array
Arr_2da = np.array([[1,2,3],[4,5,6],"hello"]) # 2 dimensional array with mixed data types
print(Arr_2da)

[1 2 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#Data types in numpy are more strict than python. In numpy, all elements of an array must be of the same data type. If we try to create an array with mixed data types, numpy will upcast the elements to a common data type that can accommodate all the elements. In this case, since we have a string "hello" in the array, numpy will upcast all the elements to strings.
import numpy as np 
Arr4 = np.array([1,2,4,5,6,7,8,9], dtype=np.int8)  #Explicilty mentioning the data type of the array as np.int8
print(Arr4)  
print(type(Arr4[0]))

#Note -->  by default  the data type of an arrar is np/int64 or np.float64 depending on the type of data we provide. We can specify the data type of an array using the dtype parameter in the np.array() function. In this example, we are creating an array of integers with a data type of np.int8, which can store integers from -128 to 127.



[1 2 4 5 6 7 8 9]
<class 'numpy.int8'>


In [ ]:
#Numpy array can have the element with only one data type
import numpy as np 
Arr3 = np.array([1,2,3,"hello"]) 
print(Arr3)
print(type(Arr3[0])) # here it will print <class 'str'> because numpy will upcast all the elements to string data type to accommodate the string "hello" in the array. because hello can not be converted to int, so all the elements will be converted to string data type.

# Arr5 = np.array([1,2,3,"hello"], dtype=np.float16) # it will give error on this line since hello cannot be converted into float data type. so we cannot create an array with mixed data types in numpy. we have to specify the data type of the array and all the elements of the array must be of the same data type.
# print(type(Arr5[0]))


Arr6 = np.array([1,2,3,"10"], dtype=np.float16) # here "10" represents the numeric valueso here it will be converted into the float
print(Arr6)

['1' '2' '3' 'hello']
<class 'numpy.str_'>
[ 1.  2.  3. 10.]


In [24]:
# Range--> it return us an object ,which can be converted into list using list()
rr=range(10)

print(rr) # it will return us a range object which represents the sequence of numbers from 0 to 9
list(rr) # it will return us a list of numbers from 0 to 9

range(0, 10)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## 2.np.arange(start,stop,step)
- Above is used as range in numpy

In [29]:
#Range in Numpy
import numpy as np 
rr_np = np.arange(10) # it will return us a numpy array which represents the sequence of numbers from 0 to 9
rr_np

rr_np_2 = np.arange(1,11,2)
print(rr_np_2) # it will return us a numpy array which represents the sequence of numbers from 1 to 10 with a step of 2

#Note


[1 3 5 7 9]


## 3. np.linspace(start,stop,num=x)
- here stop is inclusive
- here num=x represent the number i.e how many number need to be printed , those number will be printed at equal distance
- np.linspace() is used when you want to generate a fixed number of evenly spaced values between two numbers.

In [31]:
import numpy as np 
linspace_=np.linspace(1,100,4) # it will return us a numpy array which represents the sequence of numbers from 0 to 10 with 5 equally spaced values
print(linspace_)

[  1.  34.  67. 100.]


## 4.np.zero(shape)
- shape here is shape of matrix
- image is also the matrix , if we used the 2 mega pixel it means it has 2 millons data point and each of these will have value ranging 0 to 255, (0 to 255) represents the colur range it faint to bright
- it will have zeros in the matrix element

In [ ]:
import numpy as np 
oneDimensional=np.zeros(5) #one dimenional array of zeros with 5 elements
print(oneDimensional)
twoDimensional=np.zeros((5,5)) #2 dimenional array of zeros with 5 elements ->5 rows and 5 columns
print(twoDimensional)
threeDimensional=np.zeros((5,5,5)) #3 dimenional array of zeros with 6 elements --> (5,5,5) here first 5 represents the number of matrices, second 5 represents the number of rows and third 5 represents the number of columns
print(threeDimensional)

#Method to check array dimension is .ndim
threeDimensional.ndim # it will return us the number of dimensions of the array

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


3

##  5. np.ones(shape)
- this is same as above but it will create matrix with value one as element

In [3]:
import numpy as np 
np1=np.ones((2,3)) # it will give us an error because the correct syntax for creating an array of ones is np.ones((2,3)) where we need to pass a tuple as the shape of the array.
print(np1)

[[1. 1. 1.]
 [1. 1. 1.]]


## 6.np.full(shape,fill_value)
- in this we can pass the value as the matrx element

In [ ]:
import numpy as np 

npf=np.full((2,3),5) # it will return us a numpy array of shape (2,3) filled with the value 5
print(npf)

## 7. np.eye(shape)
- does not exist in 1D
- min of 2D shape
- It will create the identity matrix(matrix whose diagonal is 1)

In [6]:
import numpy as np 

neye=np.eye(5) # it will return us a 2 dimensional array of shape (5,5) with 1's on the diagonal and 0's elsewhere
print(neye)

neye_2 = np.eye(3,4) # it will return us a 2 dimensional array of shape (3,4) with 1's on the diagonal and 0's elsewhere
print(neye_2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## 8. np.empty
- this method will create the array with empty values, later values can be assigned to it
- but we cannot assigned the empty values , so here garbage collector will assigned the value which are not in used

In [ ]:
import numpy as np 

np.empty((2,3)) # it will return us a numpy array of shape (2,3) filled with random values. The values are not initialized and can be anything. It is faster than np.zeros() and np.ones() because it does not initialize the values. It is useful when we want to create an array and fill it with values later.
print(np.empty((2,3)))

''' 
in np.ones --> here 2 instruction are passed , first to create the arrray and fill array with value 1
but in np.empty --> here only one instruction is passed , first to create the arrray and assigend any vlaue to it. so it is faster than np.ones() and np.zeros() because it does not initialize the values. It is useful when we want to create an array and fill it with values later. 
'''

[[1. 1. 1.]
 [1. 1. 1.]]


## 9.np.random.rand(shape)
- will assign random values between 0 to 1
- 

In [13]:
import numpy as np 

nprandom=np.random.rand(2,3) # it will return us a numpy array of shape (2,3) filled with random values between 0 and 1
print(nprandom)

''' 
1 dimensional matrix is called the vector, 2 dimensional matrix is called the matrix and 3 dimensional matrix is called the tensor.
'''

[[0.42451193 0.49014064 0.22807804]
 [0.79347972 0.1087412  0.58244261]]


' \n1 dimensional matrix is called the vector, 2 dimensional matrix is called the matrix and 3 dimensional matrix is called the tensor.\n'

## Numpy Array Attributes



### 1. ndarray.shape

In [16]:
import numpy as np 
arr= np.array([[1,2,3,4,5],[1,4,5,6,7]]) # it will return us a numpy array of shape (2,5) which is a 2 dimensional array
print(arr.shape) # it will return us the shape of the array which is (2,5) here it represents that the array has 2 rows and 5 columns

(2, 5)


### 2. ndarray.ndim

In [17]:
print(arr.ndim) # it will return us the number of dimensions of the array which is 2 in this case because it is a 2 dimensional array

2


### 3.ndarray.size
- Retun the totoal number of element in the array

In [18]:
print(arr.size)

10


### 4. ndarray.dtype
- tells the data type of thr array elements

In [19]:
print(arr.dtype)

int64


### 5. ndarray.itemsize
- Return the sixe in bytes of one element 

In [20]:
print(arr.itemsize) # it will return us the size of each element in the array in bytes. In this case, since the data type of the array is int64, each element takes 8 bytes of memory. So it will return us 8.

8


### 6.ndarray.nbytes
- Total number of bytes consumed by the array

In [21]:
print(arr.nbytes) # it will return us the total number of bytes consumed by the elements of the array. In this case, since the array has 10 elements and each element takes 8 bytes of memory, the total number of bytes consumed by the elements of the array is 80 bytes. So it will return us 80.

80


### 7. ndarrar.T
- T for transpose



In [23]:
print(arr)

# now tramspose

print(arr.T) # it will return us the transpose of the array which is a 2 dimensional array of shape (5,2) where the rows and columns are interchanged.

[[1 2 3 4 5]
 [1 4 5 6 7]]
[[1 1]
 [2 4]
 [3 5]
 [4 6]
 [5 7]]


# Array Reshaping and Resizing in numpy

#### 1. reshape()
- Change shape , Wihout changing data

## Notes:

- The total number of elements must remain same
- reshape() returns a new view if possoible (no  copy)
- You can use-1 

In [ ]:
import numpy as np 
arr1 = np.array([1,2,3,4,5,6])
print(arr1.shape)

'''
the above array can be reshaoe into 
2*3
3*2
6*1
4*2 not possible because 4*2=8 which is not equal to 6

'''


arr1_reshaped = arr1.reshape(2,3) # it will return us a numpy array of shape (2,3) which is a 2 dimensional array
print(arr1_reshaped)

Arr_2d_reshaped = arr1.reshape(3,2) # it will return us a numpy array of shape (3,2) which is a 2 dimensional arrayArr_2d_reshaped
print(Arr_2d_reshaped)

Arr3_reshaped = arr1.reshape(6,1) # it will return us a numpy array of shape (6,1) which is a 2 dimensional array
print(Arr3_reshaped)

#Arr4_reshaped = arr1.reshape(4,2) # it will give us an error because we cannot reshape an array of shape (6,) into a shape of (4,2) because the total number of elements in the original array is 6 which is not equal to the total number of elements in the reshaped array which is 8.

# Note--> if we want to create n number of rows but we dont know how many element are present in the matrix at such time we make use if -1 , it auto decide how many columns to be creted based on the element present in the matrix
# similarly if want to create n number of column we use the same
# 9 element cant be reshaped into 4*2 because 4*2=8 which is not equal to 9 but it can be reshaped into 3*3 because 3*3=9 which is equal to the total number of elements in the original array.
#example

qee = np.array([1,2,3,4,5,6,7,8,9])
reshaped_array=qee.reshape(3,-1)
print(reshaped_array) # it will return us a numpy array of shape (3,3) which is a 2 dimensional array where the number of rows is 3 and the number of columns is automatically determined based on the total number of elements in the original array. In this case, since there are 9 elements in the original array, the number of columns will be 3 to accommodate all the elements in the reshaped array.
reshaped_array_2=qee.reshape(-1,3)
print(reshaped_array_2) # it will return us a numpy array of shape (3,3) which is a 2 dimensional array where the number of columns is 3 and the number of rows is automatically determined based on the total number of elements in the original array. In this case, since there are 9 elements in the original array, the number of rows will be 3 to accommodate all the elements in the reshaped array.


(6,)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


##2. Ravel
- It flatens the matrix into 1 dimensional array and it return the view
- Changes Reflects in the original array(if no copy made)
- Fast and memory efficient

In [ ]:

''' 
View vs Copy in Numpy

When I mutidemensional array is created . it shares the memory of 2 boxes,but when we use ravel it flattens the array to 1 dimensional array and return the view

Now What is view?
When we Used ravel a new Object is created(Instance of array) to represent the flattened array but it shares the same memory as the original array. This means that if we modify the flattened array, the changes will be reflected in the original array as well. This is because both arrays are pointing to the same memory location.
Concept of view is it does not create the new data , view is refresncing to the same memory location as original, but showing us the data in a different way. So if we modify the view, the original array will also be modified because they are sharing the same memory location. This is different from a copy, where a new memory location is created and the original array is not affected by changes made to the copy.
View is a different ndarray object that looks at the same block of memory where the actual numerical values are stored. It is a way to access the same data in a different shape or format without creating a new copy of the data. This can be useful for memory efficiency and performance, especially when working with large datasets.
'''

In [9]:
import numpy as np

a = np.array([
    [1, 2, 3, 4, 5, 6],
    [1, 6, 69, 54, 0, 0]
])
a.shape # it will return us the shape of the array which is (2,6) here it represents that the array has 2 rows and 6 columns

a_ravel=a.ravel() # it will return us a flattened view of the array which is a 1 dimensional array of shape (12,) where all the elements of the original array are stored in a single row. The ravel() function returns a view of the original array, so if we modify the flattened array, the changes will be reflected in the original array as well.
print(a_ravel) # it will return us a flattened view of the array which is a 1 dimensional array of shape (12,) where all the elements of the original array are stored in a single row. The ravel() function returns a view of the original array, so if we modify the flattened array, the changes will be reflected in the original array as well.
print(id(a)) # it will return us the memory address of the original array
print(id(a_ravel)) # it will return us the memory address of the flattened view of


[ 1  2  3  4  5  6  1  6 69 54  0  0]
2167739933168
2167739930384


In [ ]:
# .__array_interface--['data][0]

''' 
Atttriubtes in the above array gives you the actual memoery address where the raw array data begins
'''

print(a.__array_interface__['data'][0]) # it will return us the memory address of the original array where the raw array data begins
print(a_ravel.__array_interface__['data'][0]) # it will return us the memory address of the flattened view of the array where the raw array data begins. Since the flattened view is a view of the original array, both arrays share the same memory location, so the memory address will be the same as that of the original array.
# Here 


''' 
Difference between id() and .__array_interface__['data'][0]

Both id() and .__array_interface__['data'][0] give you an address-like value, but they refer to different things.

1. id()
import numpy as np

a = np.array([1, 2, 3])

print(id(a))
id(a) returns the memory address of the Python object a.
It identifies the NumPy array object itself.
This is managed by Python.

Example:

a = np.array([1, 2, 3])

print(id(a))

Output (will vary):

140234567891456

Think of it as:

NumPy array object
+-------------------+
| shape             |
| dtype             |
| strides           |
| pointer to data   |
+-------------------+

id(a) gives the address of this whole object.

2. a.__array_interface__['data'][0]
print(a.__array_interface__['data'][0])
Returns the memory address of the actual data buffer containing the array elements.
This is the location where 1, 2, 3 are stored in memory.
NumPy stores data separately from the Python object.

Example:

a = np.array([1, 2, 3])

print(a.__array_interface__['data'][0])

Output (will vary):

94383451234560

This points to:

Data buffer
+---+---+---+
| 1 | 2 | 3 |
+---+---+---+
Example
import numpy as np

a = np.array([1, 2, 3])

print("id(a):", id(a))
print("Data address:", a.__array_interface__['data'][0])

Possible output:

id(a): 140517889290224
Data address: 93948715365184

The numbers are different because they refer to different memory locations.

Summary
Feature	id(a)	a.__array_interface__['data'][0]
Refers to	Python NumPy object	Raw array data buffer
Managed by	Python	NumPy/C
Purpose	Identify the object	Locate array elements in memory
Same value?	Usually No	Usually No

So:

id(a) → "Where is the NumPy array object?"
a.__array_interface__['data'][0] → "Where are the actual numbers stored?"


'''

2167451922480
2167451922480


## 3. Flatten
- Similar to ravel but it returns the copy
- Creating the copy itself means tha it is creating the new object 

In [11]:
b=a.flatten() # it will return us a flattened copy of the array which is a 1 dimensional array of shape (12,) where all the elements of the original array are stored in a single row
print(b.__array_interface__['data'][0]) # it will return us the memory address of the flattened copy of the array where the raw array data begins. Since flatten() returns a copy of the original array, it will have a different memory address than the original array.
print(a.__array_interface__['data'][0]) # it will return us the memory address of the original array where the raw array data begins. Since flatten() returns a copy of the original array, it will have a different memory address than the original array. So it will return us a different memory address than that of the original array.

2167451921248
2167451922480


### 4. Resize()
- Ressize array in -place
- Unlike reshape(), it can change total size. data may be trauncated or padded with zeros

In [ ]:
import numpy as np

qq = np.array([
    [1, 2, 3, 4, 5, 6],
    [1, 6, 69, 54, 0, 0]
])

qq.reshape(3,4) # it will return us a reshaped view of the array which is a 2 dimensional array of shape (3,4) where the rows and columns are interchanged. The reshape() function returns a view of the original array, so if we modify the reshaped array, the changes will be reflected in the original array as well.
# qq.reshape(3,8) # it will give us an error because we cannot reshape an array of shape (2,6) into a shape of (3,8) because the total number of elements in the original array is 12 which is not equal to the total number of elements in the reshaped array which is 24.

# but we can do it with the help of resize() function which will return us a reshaped copy of the array which is a 2 dimensional array of shape (3,8) where the rows and columns are interchanged. The resize() function returns a copy of the original array, so if we modify the resized array, the changes will not be reflected in the original array.  

qq.resize((3,8), refcheck=False) # it will return us a reshaped copy of the array which is a 2 dimensional array of shape (3,8) where the rows and columns are interchanged. The resize() function returns a copy of the original array, so if we modify the resized array, the changes will not be reflected in the original array.
qq # it will return us a reshaped copy of the array which is a 2 dimensional array of shape (3,8) where the rows and columns are interchanged. The resize() function returns a copy of the original array, so if we modify the resized array, the changes will not be reflected in the original array.


#In place means changing rthe data without re-assignment
#resize vreturns none 

array([[ 1,  2,  3,  4,  5,  6,  1,  6],
       [69, 54,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

## 5. squeeze()
- remove single  dimensional axes
- Useful for emoving extra dimension from image or modal output shapes like (1,28,28,1)

In [ ]:
import numpy as np

x=np.array([[[1],[2],[3],[4],[5],[6]]]) #Here 1,2,3... are the important nuimber rest is the extra dimension which is not important 
y=x.squeeze() # it will return us a squeezed view of the array which is a 1 dimensional array of shape (6,) where all the elements of the original array are stored in a single row. The squeeze() function removes single-dimensional entries from the shape of the array, so if we modify the squeezed array, the changes will be reflected in the original array as well.
print(y) # it will return us a squeezed view of the array which is a 1
# It return tyhe new array with the same data but with a different shape. The original array remains unchanged, and the squeezed array is a view of the original array, so if we modify the squeezed array, the changes will be reflected in the original array as well.

[1 2 3 4 5 6]


# Indexing and Slicing in Numpy -- Beginner To Advanced

## 1. Indexing 1D array

In [ ]:
import numpy as np

#Slicing syntax in numpy is similar to python list slicing syntax. We can use the colon operator (:) to slice the array. The syntax is as follows:
# array[start:stop:step]

arr=np.array([10,20,30,40,50,60,70,80,90,100]) # it will return us a numpy array of shape (10,) which is a 1 dimensional array
# we need  to get 20,30,40 , we use the slicing syntax as follows:
arr[1:4] # it will return us a sliced view of the array which is a 1 dimensional array of shape (3,) where the elements at indices 1, 2, and 3 of the original array are stored. The slicing operation returns a view of the original array, so if we modify the sliced array, the changes will be reflected in the original array as well.
# array[start:stop(exclusive):step]


## UseCase [10,20,30,40,50,60,70,80,90,100] we need to get 20,40,60,80
arr[1:9:2] # it will return us a sliced view of the array which is a 1 dimensional array of shape (4,) where the elements at indices 1, 3, 5, and 7 of the original array are stored. The slicing operation returns a view of the original array, so if we modify the sliced array, the changes will be reflected in the original array as well.    

arr[::2] #here if wedont mentioned any of the vlaues it will take th first value and 2nd one will trace entore element

#reversing the array
arr[::-1] # it will return us a sliced view of the array which is a 1 dimensional array of shape (10,) where the elements of the original array are stored in reverse order. The slicing operation returns a view of the original array, so if we modify the sliced array, the changes will be reflected in the original array as well.



array([10, 30, 50, 70, 90])

## 2. Indexing 2D Array

In [ ]:
import numpy as np
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]]) # it will return us a numpy array of shape (3,3) which is a 2 dimensional array#
# In Array we do get the elememt using line mat[index][index]
#But in matrix to get th element we can simply use mat[index, index]

matrix[0][1]
matrix[0,1] 
#Both of the above will get the same output

#If i want to get 3 6 9 in a single go
matrix[:,2] #i.e i need the second column of the rows
#If I need the 2 3 5 6 of the matrix
matrix[0:2,1:] #the first parameter 0:2 tells how many rows we need(0:2) this tell 2 rows are selected and "1:" tells how many column you need
#If I need to reverse the row and the column together
''' 
[[9 8 7]
[6 5 4]
[3 2 1]]
'''
matrix[::-1,::-1] #First reverse column and then reverse rows



array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

# 3. Boolean Indexing


In [18]:
# Example to  get the elment which are greate than 15
import numpy as np
wer=np.array([5,10,15,25,30])

qq=wer[wer>15]
qq



array([25, 30])

# 4. Fancy Indexing

In [ ]:
import numpy as np

arr=np.array([100,200,300,400])
indices=[0,2,3]
print(arr[indices])


import numpy as np
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

matrix[[0,1]
       ,[2,2]]

''' 

       col0 col1 col2
row0    1    2    3
row1    4    5    6
row2    7    8    9

When you do:

matrix[[0,1], [2,2]]

NumPy performs advanced indexing. It pairs the indices element-by-element:

(0,2) → row 0, column 2 → 3
(1,2) → row 1, column 2 → 6

'''

[100 300 400]


## 5. Modifiying with indexing

In [12]:
import numpy as np

arr=np.array([100,200,300,400])
arr[2]=50
arr

arr[arr>300]=10 # it says anything greater then 400 then it will replace by 10
print(arr)

idx=np.where(arr>50) #Where will give the index ofthe element which are greate than 50
print(idx)

print(      arr[idx]) # Here it will give the element wich has the index of idx


[100 200  50  10]
(array([0, 1]),)
[100 200]
